[package]
name = "riscv-final-test"
version = "0.1.0"
authors = ["tomGER <github@tomger.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
longan-nano = "0.2.0"
riscv-rt = "0.8.0"
panic-halt = "0.2.0"